name: Backend Deploy (Production)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-production-deploy.yml"

env:
  APP_NAME: registry
  IMAGE_TYPE: apinest-backend
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: ${{ vars.REGISTRY }}
  WEBHOOK_URL: ${{ secrets.REDEPLOY_BE_WEBHOOK }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-latest
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-buildcache
            type=gha
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-buildcache,mode=max
            type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            DATABASE_URL= ${{ env.DATABASE_URL }}

      - name: Trigger Re-deployment
        if: env.WEBHOOK_URL != ''
        run: |
          curl -X POST "${{ env.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            --fail --silent --show-error
