name: Frontend Deploy (Production)

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**" # Only trigger if frontend files changed
      - ".github/workflows/frontend-production-deploy.yml"

env:
  APP_NAME: apinest
  IMAGE_TYPE: frontend
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: ${{ vars.REGISTRY }}
  WEBHOOK_URL: ${{ secrets.REDEPLOY_WEBHOOK }}
  NEXT_PUBLIC_API_URL: ${{ vars.API_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        run: |
          pnpm install --filter frontend

      - name: Build frontend
        run: |
          cd frontend
          pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/nabinkawan/${{ env.APP_NAME }}:${{ env.IMAGE_TYPE }}-buildcache,mode=max
          build-args: |
            NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}

      - name: Trigger Re-deployment
        if: env.WEBHOOK_URL != ''
        run: |
          curl -X POST "${{ env.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"service": "${{ env.APP_NAME }}", "action": "redeploy"}' \
            --fail --silent --show-error
